[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = []
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu"]
# Which actions to run on pull requests
pr-run-mode = "plan"
# The archive format to use for non-windows builds (defaults .tar.xz)
unix-archive = ".tar.gz"
# Whether to consider the binaries in a package for distribution (defaults true)
dist = true

[dist.github-custom-runners]
global = "ubuntu-latest"
x86_64-unknown-linux-gnu = "ubuntu-latest"
x86_64-apple-darwin = "macos-13"
aarch64-apple-darwin = "macos-latest"
