name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-15, macos-15-intel]
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-test-1

      - name: Run Tests
        run: cargo test

  aggregate:
    name: test:required
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: check result
        if: ${{ needs.test.result != 'success' }}
        run: exit 1
